#   -h, --help            show this help message and exit
#   -d DIRECTORY, --directory DIRECTORY
#                         Select which directory to distribute
#   -s STYLE, --style STYLE
#                         Select a CSS style sheet to include
#   -v, --verbose         Print verbose debug output
#   -t, --thumbnail       Generate 450x450 thumbnails for images
#   -n, --no-template     Don't use the template to output html
#   -nf, --no-filenames   Don't add file names to listing
#   -c, --captions        Adds image captions based on EXIF metadata, requires 'exiftool'
#   -r, --remove-index    Recursively removes all instances of index.html that have been previously made by distribusi
#   -e [DIR [DIR ...]], --exclude-directory [DIR [DIR ...]]
#                         Exclude one or multiple directories from indexing
#   -f, --force           Force whether distribusi overwrites or removes instances of index.html not generated by
#                         distribusi, use at own risk!
#   --no-hidden           Exclude hidden directories
#   --menu-with-index     Append index.html to menu items to aid navigation

python distribusi/test.py -d ./data/
